### ISSUE TITLE
BT Connectivity - RasPi BT connection failure mode - repeatedly resets

### ISSUE THREAD

**Issue by ghost** [PDXostc/rvi_mobile_unlock#4]
I’m now consistently encountering a failure that appears to be BT connectivity resetting itself periodically every ~1-2 seconds on the RasPi.
Generally, this occurs after the RasPi has been running a while.
E.g. RVI and BT boot up fine and are able to accept RVI commands without issue, but after ~5 minutes of uptime, the issue starts.

Issue manifests itself with the following error message on the RasPi (rvi_core console) and mobile app (LogCat)… see logs below.
I'm thinking this might be a hardware issue with the BT dongle or how I have it configured? Setup is using a Kensington Bluetooth 4.0 USB Adapter P/N K33956AM.

**Mobile app shows BT socket closed**

Android system logs

``` java
9-09 12:06:56.509    2289-2559/? W/bt-btif﹕ invalid rfc slot id: 20395
09-09 12:06:56.634    2289-2339/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
09-09 12:06:56.793    2289-2350/? W/bt-sdp﹕ process_service_search_attr_rsp
09-09 12:06:56.802    2289-2305/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
09-09 12:06:56.845    2289-2339/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
09-09 12:06:56.928    2289-2305/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
09-09 12:06:56.947    2289-2350/? E/bt-btif﹕ DISCOVERY_COMP_EVT slot id:20367, failed to find channle,                                       status:1, scn:0
09-09 12:06:56.947    2289-2559/? W/bt-btif﹕ invalid rfc slot id: 20367
09-09 12:06:56.948    2289-2350/? E/bt-rfcomm﹕ RFCOMM_CreateConnection - already opened state:2, RFC state:4, MCB state:5
09-09 12:06:56.948    2289-2350/? E/bt-btif﹕ bta_jv_rfcomm_connect, RFCOMM_CreateConnection failed
09-09 12:06:56.948    2289-2559/? W/bt-btif﹕ invalid rfc slot id: 20400
09-09 12:06:57.183    2289-2305/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
09-09 12:06:57.254    2289-2339/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
09-09 12:06:57.318    2289-2350/? W/bt-sdp﹕ process_service_search_attr_rsp
09-09 12:06:57.386    2289-2350/? E/bt-btif﹕ DISCOVERY_COMP_EVT slot id:20369, failed to find channle,                                       status:1, scn:0
09-09 12:06:57.386    2289-2559/? W/bt-btif﹕ invalid rfc slot id: 20369
09-09 12:06:57.390    2289-2350/? E/bt-rfcomm﹕ RFCOMM_CreateConnection - already opened state:2, RFC state:4, MCB state:5
09-09 12:06:57.390    2289-2350/? E/bt-btif﹕ bta_jv_rfcomm_connect, RFCOMM_CreateConnection failed
09-09 12:06:57.393    2289-2559/? W/bt-btif﹕ invalid rfc slot id: 20403
09-09 12:06:57.507    2289-2339/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
09-09 12:06:57.572    2289-2305/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
09-09 12:06:57.591    2289-2350/? W/bt-sdp﹕ process_service_search_attr_rsp
09-09 12:06:57.669    2289-2350/? E/bt-btif﹕ DISCOVERY_COMP_EVT slot id:20370, failed to find channle,                                       status:1, scn:0
09-09 12:06:57.669    2289-2559/? W/bt-btif﹕ invalid rfc slot id: 20370
09-09 12:06:57.675    2289-2350/? E/bt-rfcomm﹕ RFCOMM_CreateConnection - already opened state:2, RFC state:4, MCB state:5
09-09 12:06:57.675    2289-2350/? E/bt-btif﹕ bta_jv_rfcomm_connect, RFCOMM_CreateConnection failed
09-09 12:06:57.676    2289-2559/? W/bt-btif﹕ invalid rfc slot id: 20406
09-09 12:06:57.690    2289-2305/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
09-09 12:06:57.935    2289-2339/? D/BTIF_SOCK﹕ service_uuid: 00001101-0000-1000-8000-00805f9b34fb
```

Mobile app logs

``` java
09-06 23:20:21.623  26275-28964/com.jaguarlandrover.auto.remote.vehicleentry W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-06 23:19:41.372  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry D/RVI﹕ Excepption:read failed, socket might closed or timeout, read ret: -1
09-06 23:19:41.372  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
09-06 23:19:46.501  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ java.io.IOException: read failed, socket might closed or timeout, read ret: -1
09-06 23:19:46.502  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:512)
09-06 23:19:46.502  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:489)
09-06 23:19:46.502  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:319)
09-06 23:19:46.502  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at com.jaguarlandrover.auto.remote.vehicleentry.RviService$4.call(RviService.java:614)
09-06 23:19:46.503  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at com.jaguarlandrover.auto.remote.vehicleentry.RviService$4.call(RviService.java:584)
09-06 23:19:46.515  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at rx.Observable.unsafeSubscribe(Observable.java:7304)
09-06 23:19:46.515  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
09-06 23:19:46.515  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
09-06 23:19:46.515  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
09-06 23:19:46.515  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-06 23:19:46.516  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
09-06 23:19:46.516  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
09-06 23:19:46.516  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-06 23:19:46.516  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-06 23:19:46.516  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
09-06 23:19:46.517  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry I/RVI﹕ Sending to socket authandroid.bluetooth.BluetoothSocket@21715ba4
09-06 23:19:46.518  26275-28179/com.jaguarlandrover.auto.remote.vehicleentry E/RVI﹕ Resetting .....
09-06 23:19:46.540  26275-26430/com.jaguarlandrover.auto.remote.vehicleentry E/RVI﹕ java.io.IOException: Broken pipe
            at android.net.LocalSocketImpl.writeba_native(Native Method)
            at android.net.LocalSocketImpl.access$600(LocalSocketImpl.java:33)
            at android.net.LocalSocketImpl$SocketOutputStream.write(LocalSocketImpl.java:135)
            at android.bluetooth.BluetoothSocket.write(BluetoothSocket.java:442)
            at android.bluetooth.BluetoothOutputStream.write(BluetoothOutputStream.java:85)
            at java.io.OutputStream.write(OutputStream.java:82)
            at com.jaguarlandrover.auto.remote.vehicleentry.RviService$4.call(RviService.java:633)
            at com.jaguarlandrover.auto.remote.vehicleentry.RviService$4.call(RviService.java:584)
            at rx.Observable.unsafeSubscribe(Observable.java:7304)
            at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**rvi_core console shows bt/stoffe/{service name} as disappeared**
Service disappeared showing up on rvi_core logs when attempting a service.
Because of this, no services get through to the RasPi's Python script.

``` erlang
(rvi@127.0.0.1)1> 
(rvi@127.0.0.1)1> c_src/bt_linux_drv.c:388: rfcomm_running: 5 has input
c_src/bt_linux_drv.c:389: rfcomm_running: sub 0x1bab730
c_src/bt_linux_drv.c:390: rfcomm_running: id 23
00:51:55.653 [debug] bt_connection:handle_info(data): Data: <<"{"tid":2,"cmd":"rcv","mod":"proto_json_rpc","data":"eyJzZXJ2aWNlIjoiamxyLmNvbVwvYnRcL3N0b2ZmZVwvdW5sb2NrIiwidGltZW91dCI6MTQzMzI2\nNjcwNCwicGFyYW1ldGVycyI6W3sidXNlcm5hbWUiOiIwIiwidmVoaWNsZVZJTiI6IjAiLCJsYXRp\ndHVkZSI6MzMuODM5MjIyMDksImxvbmdpdHVkZSI6LTExNy45MjM2MjIwOX1dLCJjZXJ0aWZpY2F0\nZSI6IiIsInNpZ25hdHVyZSI6IiJ9\n"}">>
00:51:55.655 [info] bt_connection:handle_info(data): From: {12,72,133,32,86,25}:1 
00:51:55.656 [info] bt_connection:handle_info(data): {12,72,133,32,86,25}:1 -> dlink_bt_rpc:handle_socket
00:51:55.657 [debug] dlink_bt:data(): Got [{"tid",2},{"cmd","rcv"},{"mod","proto_json_rpc"},{"data","eyJzZXJ2aWNlIjoiamxyLmNvbVwvYnRcL3N0b2ZmZVwvdW5sb2NrIiwidGltZW91dCI6MTQzMzI2\nNjcwNCwicGFyYW1ldGVycyI6W3sidXNlcm5hbWUiOiIwIiwidmVoaWNsZVZJTiI6IjAiLCJsYXRp\ndHVkZSI6MzMuODM5MjIyMDksImxvbmdpdHVkZSI6LTExNy45MjM2MjIwOX1dLCJjZXJ0aWZpY2F0\nZSI6IiIsInNpZ25hdHVyZSI6IiJ9\n"}]
00:51:55.659 [debug] dlink_bt:receive_data(): SetupAddress: {{12,72,133,32,86,25}, 1}
00:51:55.659 [debug] dlink_bt:receive_data(): "proto_json_rpc":receive_message("eyJzZXJ2aWNlIjoiamxyLmNvbVwvYnRcL3N0b2ZmZVwvdW5sb2NrIiwidGltZW91dCI6MTQzMzI2\nNjcwNCwicGFyYW1ldGVycyI6W3sidXNlcm5hbWUiOiIwIiwidmVoaWNsZVZJTiI6IjAiLCJsYXRp\ndHVkZSI6MzMuODM5MjIyMDksImxvbmdpdHVkZSI6LTExNy45MjM2MjIwOX1dLCJjZXJ0aWZpY2F0\nZSI6IiIsInNpZ25hdHVyZSI6IiJ9\n")
00:51:55.661 [debug] Sending protocol - proto_json_rpc:receive_message(["{"service":"jlr.com\/bt\/stoffe\/unlock","timeout":1433266704,"parameters":[{"username":"0","vehicleVIN":"0","latitude":33.83922209,"longitude":-117.92362209}],"certificate":"","signature":""}"])
00:51:55.663 [debug]     protocol:rcv(): service name:    "jlr.com/bt/stoffe/unlock"
00:51:55.664 [debug]     protocol:rcv(): timeout:         1433266704
00:51:55.665 [debug]     protocol:rcv(): signature:       []
00:51:55.665 [debug]     protocol:rcv(): certificate:     []
00:51:55.666 [debug] Sending service_edge - service_edge_rpc:handle_remote_message(["jlr.com/bt/stoffe/unlock",1433266704,{array,[{struct,[{"username","0"},{"vehicleVIN","0"},{"latitude",33.83922209},{"longitude",-117.92362209}]}]},[],[]])
00:51:55.667 [debug] service_edge:remote_msg(): service_name:    "jlr.com/bt/stoffe/unlock"
00:51:55.668 [debug] service_edge:remote_msg(): timeout:         1433266704
00:51:55.669 [debug] service_edge:remote_msg(): parameters:      {array,[{struct,[{"username","0"},{"vehicleVIN","0"},{"latitude",33.83922209},{"longitude",-117.92362209}]}]}
00:51:55.670 [debug] service_edge:remote_msg(): signature:       []
00:51:55.670 [debug] service_edge:remote_msg(): certificate:     []
00:51:55.671 [notice] service_entry:remote_msg(): Service Disappeared "jlr.com/bt/stoffe/unlock"
```

The closed/restarted BT connection might be the cause of RVI losing the service hosted on the mobile phone side.

**Comment by ghost** [comment]
Checking hciconfig on the RasPi all seems fine, no errors. Checking on the phone side.

**hciconfig**

``` linux
pi@raspi /var/log $ hciconfig
hci0:   Type: BR/EDR  Bus: USB
    BD Address: 00:1B:DC:06:A0:B1  ACL MTU: 310:10  SCO MTU: 64:8
    UP RUNNING 
    RX bytes:467346 acl:15530 sco:0 events:16663 errors:0
    TX bytes:325560 acl:15535 sco:0 commands:472 errors:0
```

**/var/log/messages** - filtered for 'usb' and 'Bluetooth'

``` linux
Sep  9 17:17:43 raspi kernel: [3.617940] usb 1-1.3: new full-speed USB device number 4 using dwc_otg
Sep  9 17:17:43 raspi kernel: [4.163246] usb 1-1.3: New USB device found, idVendor=0a12, idProduct=0001
Sep  9 17:17:43 raspi kernel: [4.171990] usb 1-1.3: New USB device strings: Mfr=0, Product=2, SerialNumber=0
Sep  9 17:17:43 raspi kernel: [4.181142] usb 1-1.3: Product: CSR8510 A10

Sep  9 17:17:43 raspi kernel: [14.862193] Bluetooth: Core ver 2.19
Sep  9 17:17:43 raspi kernel: [14.862357] Bluetooth: HCI device and connection manager initialized
Sep  9 17:17:43 raspi kernel: [14.862402] Bluetooth: HCI socket layer initialized
Sep  9 17:17:43 raspi kernel: [14.862418] Bluetooth: L2CAP socket layer initialized
Sep  9 17:17:43 raspi kernel: [14.862469] Bluetooth: SCO socket layer initialized
Sep  9 17:17:45 raspi kernel: [29.591562] Bluetooth: RFCOMM TTY layer initialized
Sep  9 17:17:45 raspi kernel: [29.591612] Bluetooth: RFCOMM socket layer initialized
Sep  9 17:17:45 raspi kernel: [29.591654] Bluetooth: RFCOMM ver 1.11
Sep  9 17:17:45 raspi kernel: [29.611279] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Sep  9 17:17:45 raspi kernel: [29.611299] Bluetooth: BNEP filters: protocol multicast
Sep  9 17:17:45 raspi kernel: [29.611333] Bluetooth: BNEP socket layer initialized
```

**/var/log/messages** - filtered for 'bluetooth'

``` linux
Sep  9 13:17:18 raspi bluetoothd[2383]: Bluetooth daemon 4.99
Sep  9 13:17:18 raspi bluetoothd[2383]: Starting SDP server
Sep  9 13:17:18 raspi bluetoothd[2383]: Excluding (conf) pnat
Sep  9 13:17:18 raspi bluetoothd[2383]: Failed to init alert plugin
Sep  9 13:17:18 raspi bluetoothd[2383]: Failed to init time plugin
Sep  9 13:17:18 raspi bluetoothd[2383]: Failed to init gatt_example plugin
Sep  9 13:17:18 raspi bluetoothd[2383]: Listening for HCI events on hci0
Sep  9 13:17:19 raspi bluetoothd[2383]: HCI dev 0 up
Sep  9 13:17:19 raspi bluetoothd[2383]: Proximity GATT Reporter Driver: Operation not permitted (1)
Sep  9 13:17:19 raspi bluetoothd[2383]: Could not get the contents of DMI chassis type
Sep  9 13:17:19 raspi bluetoothd[2383]: input-headset driver probe failed for device 0C:48:85:20:56:19
Sep  9 13:17:19 raspi bluetoothd[2383]: input-headset driver probe failed for device 1C:56:FE:B7:89:25
Sep  9 13:17:19 raspi bluetoothd[2383]: Unable to load keys to adapter_ops: Function not implemented (38)
Sep  9 13:17:19 raspi bluetoothd[2383]: Adapter /org/bluez/2383/hci0 has been enabled
Sep  9 17:17:44 raspi bluetoothd[2345]: Bluetooth daemon 4.99
Sep  9 17:17:44 raspi bluetoothd[2345]: Starting SDP server
Sep  9 17:17:44 raspi bluetoothd[2345]: Excluding (conf) pnat
Sep  9 17:17:45 raspi bluetoothd[2345]: Failed to init alert plugin
Sep  9 17:17:45 raspi bluetoothd[2345]: Failed to init time plugin
Sep  9 17:17:45 raspi bluetoothd[2345]: Failed to init gatt_example plugin
Sep  9 17:17:45 raspi bluetoothd[2345]: Listening for HCI events on hci0
Sep  9 17:17:45 raspi bluetoothd[2345]: HCI dev 0 up
Sep  9 17:17:45 raspi bluetoothd[2345]: Proximity GATT Reporter Driver: Operation not permitted (1)
Sep  9 17:17:45 raspi bluetoothd[2345]: Could not get the contents of DMI chassis type
Sep  9 17:17:45 raspi bluetoothd[2345]: input-headset driver probe failed for device 0C:48:85:20:56:19
Sep  9 17:17:45 raspi bluetoothd[2345]: input-headset driver probe failed for device 1C:56:FE:B7:89:25
Sep  9 17:17:45 raspi bluetoothd[2345]: Unable to load keys to adapter_ops: Function not implemented (38)
Sep  9 17:17:45 raspi bluetoothd[2345]: Adapter /org/bluez/2345/hci0 has been enabled
```

**Comment by ghost** [comment]
Android system logs added to opening comment. Multiple instances of error...

``` java
09-09 12:06:56.947    2289-2350/? E/bt-btif﹕ DISCOVERY_COMP_EVT slot id:20367, failed to find channle,                                       status:1, scn:0
09-09 12:06:56.948    2289-2350/? E/bt-rfcomm﹕ RFCOMM_CreateConnection - already opened state:2, RFC state:4, MCB state:5
09-09 12:06:56.948    2289-2350/? E/bt-btif﹕ bta_jv_rfcomm_connect, RFCOMM_CreateConnection failed
```

**Comment by magnusfeuer** [comment]
(Responding from my private email since my JLR credentials have yet to 
be restored)

David,

I can only say that the link is lost, which RVI reacts correctly to by 
deleting the service.

Can you post the content of your unlock.sh file, please.

/Magnus F.

**Comment by ghost** [comment]
Hi Magnus,

Thanks! I'm noticing the same wrt to rvi_core, it's handling the frequent link resets fine.
_unlock.sh_ added below. Also, included below it is another support script I wrote to periodically connect to our trusted phones, _unlock_prioritized_devices.sh_. 
I've also tested with my added support script disabled and still seeing the same connectivity error.

**./unlock.sh**

``` shell
#!/bin/sh

cd ~/rvi_core/
sudo ./rel/raspi_node/bin/rvi start
# sudo ./rel/raspi_node_local_home/bin/rvi start

sleep 10

sudo hcitool -i hci0 cmd 0x08 0x0008 1E 02 01 1A 1A FF 4C 00 02 15 33 43 33 43 46 46 47 45 38 45 54 32 39 31 34 30 39 00 00 00 C5 00
sudo hcitool -i hci0 cmd 0x08 0x0006 A0 00 A0 00 03 00 00 00 00 00 00 00 00 07 00
sudo hcitool -i hci0 cmd 0x08 0x000a 01

sleep 12

cd ~/rvi_raspi/; sudo ./unlock_prioritized_devices.sh &

echo rvi_core pid:
cd ~/rvi_core/
sudo ./rel/raspi_node/bin/rvi getpid
# sudo ./rel/raspi_node_local_home/bin/rvi getpid

while true
do
        (cd ~/rvi_raspi/python/; sudo python fob.py)
        sleep 5
done
```

**./unlock_prioritized_devices.sh**

``` shell
#!/bin/sh

while true
do
    sudo hcitool cc {Bluetooth Mac}
    sleep 3
    sudo hcitool cc {Bluetooth Mac}
    sleep 3
done
```
